version: '3'

services:
  nginx-abxtest:
    profiles: [ "prod_frontend" ]
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      - NGINX_HOST=abxtest.com
      - NGINX_INDEX=index.html
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-abxtest.rule=Host(`abxtest.com`)
      - traefik.http.routers.nginx-abxtest.entrypoints=websecure
      - traefik.http.routers.nginx-abxtest.tls=true
      - traefik.http.routers.nginx-abxtest.tls.certresolver=letsencrypt
      - traefik.http.services.nginx-abxtest.loadbalancer.server.port=80
    networks:
      - web

  nginx-abxtest-loc:
    profiles: [ "dev_frontend" ]
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html

  mock_api:
    profiles: [ "mock_api" ]
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./docker/mock/:/usr/share/nginx/html/
      - ./docker/mock/hosts/default.conf:/etc/nginx/conf.d/default.conf

networks:
  web:
    external: true # стандартная для всех на этом сервере