version: '3.8'
services:
  webpack:
    profiles: [ "frontend" ]
    container_name: webpack
    build: ./docker/webpack/Dockerfile
    volumes:
      - .:/app
    ports:
      - "9090:9090"
    command: npm run serve
  mock_api:
    profiles: [ "mock_api" ]
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/mock/:/usr/share/nginx/html/