version: '3'

services:
  nginx-abxtest:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      - NGINX_HOST=abxtest.com
      - NGINX_INDEX=index.html
      - NGINX_ROOT=/usr/share/nginx/html
      - NGINX_PORT=80
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-abxtest.rule=Host(`abxtest.com`)
      - traefik.http.routers.nginx-abxtest.entrypoints=websecure
      - traefik.http.routers.nginx-abxtest.tls=true
      - traefik.http.routers.nginx-abxtest.tls.certresolver=letsencrypt
      - traefik.http.services.nginx-abxtest.loadbalancer.server.port=80
    networks:
      - web

networks:
  web:
    external: true # стандартная для всех на этом сервере