
services:

  abx-nginx:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/public/
      - ./dist:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.abx-nginx.rule=Host(`abxtest.com`)
      - traefik.http.routers.abx-nginx.entrypoints=websecure
      - traefik.http.routers.abx-nginx.tls=true
      - traefik.http.routers.abx-nginx.tls.certresolver=letsencrypt
      - traefik.http.services.abx-nginx.loadbalancer.server.port=80
    networks:
      - web

  abx-php:
    container_name: abx-php
    build: ./docker/php/
    expose:
      - 9003
    volumes:
      - ./backend:/var/www/public
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - web

  abx-nginx-loc:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/public/
      - ./dist:/usr/share/nginx/html
    networks:
      - web


networks:
  web:
    external: true # стандартная для всех на этом сервере