version: '3.8'
services:
  webpack:
    profiles: [ "frontend" ]
    container_name: webpack
    build: ./docker/webpack/Dockerfile
    volumes:
      - .:/app
    ports:
      - "9090:9090"
    command: npm run serve