server {
    listen 80;
    server_name abxtest.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 8080;
    server_name _;

    include /etc/nginx/snippets/app.conf;
}
